/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerIndexRouteImport } from './routes/timer/index'
import { Route as R2026IndexRouteImport } from './routes/2026/index'
import { Route as indexIndexRouteImport } from './routes/(index)/index'

const TimerIndexRoute = TimerIndexRouteImport.update({
  id: '/timer/',
  path: '/timer/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2026IndexRoute = R2026IndexRouteImport.update({
  id: '/2026/',
  path: '/2026/',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/(index)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexIndexRoute
  '/2026/': typeof R2026IndexRoute
  '/timer/': typeof TimerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexIndexRoute
  '/2026': typeof R2026IndexRoute
  '/timer': typeof TimerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(index)/': typeof indexIndexRoute
  '/2026/': typeof R2026IndexRoute
  '/timer/': typeof TimerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/2026/' | '/timer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/2026' | '/timer'
  id: '__root__' | '/(index)/' | '/2026/' | '/timer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexIndexRoute: typeof indexIndexRoute
  R2026IndexRoute: typeof R2026IndexRoute
  TimerIndexRoute: typeof TimerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer/': {
      id: '/timer/'
      path: '/timer'
      fullPath: '/timer/'
      preLoaderRoute: typeof TimerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2026/': {
      id: '/2026/'
      path: '/2026'
      fullPath: '/2026/'
      preLoaderRoute: typeof R2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/': {
      id: '/(index)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexIndexRoute: indexIndexRoute,
  R2026IndexRoute: R2026IndexRoute,
  TimerIndexRoute: TimerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
